# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Chang
tagline:          'Theoretical Particle Physics, INFN Genova'
description:      'QCD, scattering, transverse momentum, Jet, <a>Theoretical</a>, collider, Higgs, Field Theory, shower, resummation, <a>Particle</a>, numerical, Drell-Yan, gluon, inclusive, high-order, <a>Physicist</a>, perturbative, logarithm, Monte Carlo.'
url:              http://cwu137.github.io
baseurl:          http://cwu137.github.io

author:
  name:           'Chang Wu'
  url:            https://twitter.com/cwu34

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cwu137
  research:       https://cwu137.github.io/Research/ 

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
