# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none
# relative_permalinks: true

# Setup
title:            Chang
tagline:          'Theoretical Particle Physics, INFN Genova'
description:      'QCD, scattering, transverse momentum, Jet, <a>Theoretical</a>, collider, Higgs, Field Theory, shower, standard, resummation, <a>Particle</a>, numerical, Drell-Yan,gluon, high-order, <a>Physicist</a>, inclusive, perturbative, logarithm, Monte Carlo.'
url:              http://cwu137.github.io
baseurl:          /

author:
  name:           'Chang Wu'
  url:            https://twitter.com/cwu34

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
